kind: pipeline
type: docker
name: build

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: gigafyde/image-gen
      username: gigafyde
        password:
          from_secret: docker_token
      tags: dev
      force_tag: true
