
kind: pipeline
type: docker
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: docker-build
    image: plugins/docker
    settings:
      repo: gigafyde/image-gen
      username: gigafyde
      password:
        from_secret: dockerhub
      tags: amd64
      force_tag: true
    when:
      branch:
        - master
